language: node_js
sudo: false

os:
  - linux

node_js:
  - 8.9.0

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - npm run lint

script:
  - npm test

after_script:
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
